kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: golang:1.22.0-alpine
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - GOOS=linux GOARCH=amd64 go build -o main
  - name: build docker file and publish
    depends_on:
      - build
    image: plugins/docker:20.17
    pull: if-not-exists
    settings:
      registry: hub.ooxo.cc
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ooxo.cc/home/bark-webhook
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
